### ISSUE TITLE
How to Fix

### ISSUE THREAD

**Issue by Pandugumilang29** [Pymmdrza/BTCHDwallet#6]
how to fix this
ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

**Comment by Pymmdrza** [comment]
> how to fix this ModuleNotFoundError: No module named 'urllib3.packages.six.moves'

>[!NOTE]
> Did you even bother to check the [README](https://github.com/Pymmdrza/BTCHDwallet# 'ReadMe Bitcoin HDWallet Script Document') page? Or did you quickly choose the easiest way for yourself? I don't know how else to write a user guide...


## Install Package's with PIP

install package's in windows with `pip` : 

```cmd
pip install --upgrade colorthon requests hdwallet
```
install package's in linux with `pip3`:

```bash
sudo apt-get update&&sudo apt-get upgrade -y
sudo apt-get install python3-pip
pip3 install --upgrade colorthon requests hdwallet
```


## Auto Install & Run : 


- install package in Windows: [install.bat](https://github.com/Pymmdrza/BTCHDwallet/blob/main/install.bat)
- install package in linux : [install.sh](https://github.com/Pymmdrza/BTCHDwallet/blob/main/install.bat)
- install and running Single Script: [btcSingle.bat](https://github.com/Pymmdrza/BTCHDwallet/blob/main/btcSingle.bat 'auto install and auto run bitcoin single')

## Git : 
- windows 
```cmd
git clone https://github.com/Pymmdrza/BTCHDwallet
cd BTCHDwallet
install
```
- linux 
```shell
git clone https://github.com/Pymmdrza/BTCHDwallet
cd BTCHDwallet
sudo chmod -x install.sh
./install.sh
```

**Comment by WilliamsRegae** [comment]
BTCHD not found in my directories

**Comment by Pymmdrza** [comment]
@WilliamsRegae  check again and re-clone

**Comment by WilliamsRegae** [comment]
python3: can't open file
'/data/data/com.termux/files/home/BTCHDwallet/BTCHDW.py': [Errno 2] No such
file or directory


Please help me out.i AM using termux

**Comment by WilliamsRegae** [comment]
After implementing <python3 singleWallet.py>. This is what I got .........$ python3 singleWallet.py
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/BTCHDwallet/singleWallet.py", line 67, in <module>
    getClear()
  File "/data/data/com.termux/files/home/BTCHDwallet/singleWallet.py", line 37, in getClear
    raise ValueError('Not Supported Platform: "%s"' % platform.platform())
ValueError: Not Supported Platform: "Linux-4.14.186-g398737f70064-dirty-aarch64-with-libc"

**Comment by Pymmdrza** [comment]
> After implementing . This is what I got .........$ python3 singleWallet.py Traceback (most recent call last): File "/data/data/com.termux/files/home/BTCHDwallet/singleWallet.py", line 67, in getClear() File "/data/data/com.termux/files/home/BTCHDwallet/singleWallet.py", line 37, in getClear raise ValueError('Not Supported Platform: "%s"' % platform.platform()) ValueError: Not Supported Platform: "Linux-4.14.186-g398737f70064-dirty-aarch64-with-libc"

Clone Again and Re-Check .


Update Clear Function:
```python
def getClear():
    os.system('cls' if os.name == 'nt' else 'clear')
```

**Comment by WilliamsRegae** [comment]
Working perfectly boss thanks...

But have been running it for 24hours now and no wallets found... could this be a problem

**Comment by Pymmdrza** [comment]
> Working perfectly boss thanks...
> 
> But have been running it for 24hours now and no wallets found... could this be a problem

This is a standardized and simplified process of comparing addresses and checking their inventory, which finding a wallet is completely a matter of chance and luck, because in this project the process is non-repetitive and random, which increases the probability of finding a wallet.
