### ISSUE TITLE
Key error 

### ISSUE THREAD

**Issue by Leandroca13** [Pymmdrza/BTCHDwallet#7]
I'm trying to run the code but after start appears this error...

Start ...
Traceback (most recent call last):
  File "C:\Users\leand\Desktop\BTCHDwallet-main\singleWallet.py", line 80, in <module>
    val_et = ethBal(ethaddr)
             ^^^^^^^^^^^^^^^
  File "C:\Users\leand\Desktop\BTCHDwallet-main\singleWallet.py", line 43, in ethBal
    ret = dict(req)['balance']
          ~~~~~~~~~^^^^^^^^^^^
KeyError: 'balance'

**Comment by Pymmdrza** [comment]
> I'm trying to run the code but after start appears this error...
> 
> Start ... Traceback (most recent call last): File "C:\Users\leand\Desktop\BTCHDwallet-main\singleWallet.py", line 80, in val_et = ethBal(ethaddr) ^^^^^^^^^^^^^^^ File "C:\Users\leand\Desktop\BTCHDwallet-main\singleWallet.py", line 43, in ethBal ret = dict(req)['balance'] ~~~~~~~~~^^^^^^^^^^^ KeyError: 'balance'


### check again

```bash
git clone https://github.com/Pymmdrza/BTCHDwallet.git
cd BTCHDwallet
```
